steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - deploy
  - releases
  - create
  - backend-$COMMIT_SHA
  - --delivery-pipeline=dead-simpl
  - --region=us-central1
  - --images=backend=us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA
images:
- us-central1-docker.pkg.dev/$PROJECT_ID/backend/backend:$COMMIT_SHA
